INSERT INTO tb_users(login, password, role)
	VALUES ('user1', '$2a$05$djRHtinp5lJlKFb9omQHduQrWjOAy/fMBtRhZ0x1UqmlVcTwxZHNy', 'ROLE_ADMIN'),
	       ('user2', '$2a$05$Kumwk.MjxCPInBAPSiMXueJQRpgWglKpQ81XzQOwyKzgtWYmaS/jC', 'ROLE_USERS_VIEWER, ROLE_USERS_EDITOR, ROLE_POSTS_VIEWER, ROLE_ALBUMS_VIEWER'),
	       ('user3', '$2a$05$VYInz.urAozffxYcIkJUYu4fXhtzhH5VUc8PPkUB1xDvRRnR9Fofa', 'ROLE_USERS_VIEWER, ROLE_POSTS_VIEWER, ROLE_POSTS_EDITOR, ROLE_ALBUMS_VIEWER'),
	       ('user4', '$2a$05$WS6JEIj7XBpGA9Pxi4ABCeV3cmehVZIO9t0We.JrT9OEFR2dluyqu', 'ROLE_USERS_VIEWER, ROLE_POSTS_VIEWER, ROLE_ALBUMS_VIEWER, ROLE_ALBUMS_EDITOR'),
	       ('user5', '$2a$05$GIp3MjEFP76Fgj6vhzLNzuoDC3rkKptY.POqZJSjpFRffSVeyreM2', 'ROLE_USERS_VIEWER, ROLE_POSTS_VIEWER, ROLE_ALBUMS_VIEWER');